export default function AIAnalysis({
  event
}) {

  if (!event) {

    return (
      <div className="ai-panel">

        <h2>
          AI THREAT ANALYSIS
        </h2>

        <p>
          Waiting for security event...
        </p>

      </div>
    );
  }


  return (
    <div className="ai-panel">

      <div className="ai-header">

        <h2>
          AI THREAT ANALYSIS
        </h2>

        <span>
          LIVE
        </span>

      </div>


      <div className="analysis-grid">

        <div>
          <small>Threat</small>
          <strong>
            {event.event_type}
          </strong>
        </div>

        <div>
          <small>Risk Score</small>
          <strong>
            {event.risk_score}/100
          </strong>
        </div>

        <div>
          <small>MITRE ATT&CK</small>
          <strong>
            {event.mitre_technique}
          </strong>
        </div>

        <div>
          <small>Status</small>
          <strong>
            {event.ai_status}
          </strong>
        </div>

      </div>


      <div className="analysis-description">

        <strong>
          Synthetic Security Event
        </strong>

        <p>
          This event was generated by the
          controlled AI-IDAPS simulation
          environment and transmitted to the
          AI-IDAPS detection backend.
        </p>

      </div>

    </div>
  );
}